### ISSUE TITLE
Disqus takes a long time to load

### ISSUE THREAD

**Issue by VincentTam** [vojtechruz/vojtechruzicka-blog#2]
Hi, I've read your post about Staticman.  Disqus comments at the bottom can't be loaded in my browser.  I'm using qutebrowser on Ubuntu 18.04.

![Screenshot from 2019-07-01 11-01-58](https://user-images.githubusercontent.com/5748535/60424132-edc35000-9bef-11e9-9eb4-5095becf5a80.png)

**Comment by vojtechruz** [comment]
Thanks for reporting, I'll look into this.

**Comment by VincentTam** [comment]
Thanks for response.  Have you thought of migrating from Disqus?  Here's some articles about its shortcomings.

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/

You may try static comments for static blog comments. Comments are stored as YML files inside your repo, so that you completely own the comment. With a static blog generator, these YML files can be converted into HTML elements under your posts, so that the comments are SEO-friendly.

To illustrate this, let me use an [MR for a static comment](https://framagit.org/staticman-gitlab-pages/bhdemo/merge_requests/5) received on [my Framagit+Beautiful Hugo+Staticman demo site](https://staticman-gitlab-pages.frama.io/bhdemo/).

| Field       | Content                                                                                     |
| ----------- | ------------------------------------------------------------------------------------------- |
| replyThread |                                                                                             |
| replyID     |                                                                                             |
| replyName   |                                                                                             |
| comment     | Essai : $n!\underset{+\infty}{\sim}\left(\frac{n}{e}\right)^n\sqrt{2\pi n}$.
Ok ? :smiley: |
| name        | François Coulombeau                                                                         |
| email       | 137743b032171d66c4caa2be6b0884c3                                                            |
| website     |                                                                                             |
| date        | 2019-02-28T22:44:08.269Z                                                                    |

This is rendered as  
[![screenshot for rendered comment](http://imgur.com/KRTtJLXl.png)](https://staticman-gitlab-pages.frama.io/bhdemo/posts/my-second-post/)  
Image URL: http://imgur.com/KRTtJLXl.png  
in my page.

**Comment by vojtechruz** [comment]
Thanks for more info. Yes, i definitely want to get rid of disqus once I have some free time. Probably staticman.

**Comment by vojtechruz** [comment]
Disqus is now removed, will be replacing with new system soon.

**Comment by vojtechruz** [comment]
Added new commenting system using [Giscus](https://giscus.app/)
